"""Export Phase 2 NPZ fixtures to ``$readmemh`` vectors for ``tb_ddc``.

Derives DDC expected baseband from checked-in IF streams via
``cryocontrol.dsp_ref.ddc.ddc`` (fixtures do not store intermediate baseband).
Quantizes I/Q to signed Q1.14 (round-to-nearest, saturate).

Run from repo root (package importable)::

    python hdl/tb/ddc/export_fixtures.py

Writes under ``hdl/tb/ddc/vectors/``.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np

from cryocontrol.dsp_ref.ddc import ddc
from cryocontrol.dsp_ref.fixtures import FIXTURES_DIR, load_fixture

FRAC_BITS = 14
SCALE = 1 << FRAC_BITS
# Matches docs/fixed_point_notes.md (ddc module-TB compare).
TOL_LSB = 4

TB_DIR = Path(__file__).resolve().parent
VEC_DIR = TB_DIR / "vectors"
NOISELESS = FIXTURES_DIR / "noiseless.npz"
NOISY = FIXTURES_DIR / "noisy.npz"


def float_to_q114(x: np.ndarray) -> np.ndarray:
    """Round-nearest float → signed Q1.14 int16 codes."""
    v = np.rint(np.asarray(x, dtype=np.float64) * SCALE)
    return np.clip(v, -32768, 32767).astype(np.int16)


def q114_to_hex_lines(codes: np.ndarray) -> list[str]:
    """Two's-complement 16-bit hex, one sample per line (for ``$readmemh``)."""
    u = codes.astype(np.int16).view(np.uint16)
    return [f"{int(v):04x}" for v in u]


def write_mem(path: Path, codes: np.ndarray) -> None:
    path.write_text("\n".join(q114_to_hex_lines(codes)) + "\n", encoding="utf-8")


def phase_inc_word(fs: float, f_lo: float) -> int:
    """Unsigned 32-bit NCO tuning word: round(f_lo/fs * 2^32)."""
    return int(np.round(f_lo / fs * (1 << 32))) & 0xFFFFFFFF


def phase0_word(phase0_rad: float) -> int:
    """Unsigned 32-bit initial phase: round(phase0/(2π) * 2^32)."""
    return int(np.round(phase0_rad / (2.0 * np.pi) * (1 << 32))) & 0xFFFFFFFF


def export_case(
    name: str,
    input_iq: np.ndarray,
    *,
    fs: float,
    f_lo: float,
    phase0: float,
) -> dict:
    """Write in/exp I/Q mem files; return metadata for params."""
    baseband = ddc(input_iq, fs=fs, f_lo=f_lo, phase0=phase0)
    in_i = float_to_q114(np.real(input_iq))
    in_q = float_to_q114(np.imag(input_iq))
    exp_i = float_to_q114(np.real(baseband))
    exp_q = float_to_q114(np.imag(baseband))

    write_mem(VEC_DIR / f"{name}_in_i.mem", in_i)
    write_mem(VEC_DIR / f"{name}_in_q.mem", in_q)
    write_mem(VEC_DIR / f"{name}_exp_i.mem", exp_i)
    write_mem(VEC_DIR / f"{name}_exp_q.mem", exp_q)

    return {
        "name": name,
        "n_samples": int(input_iq.size),
        "phase_inc": phase_inc_word(fs, f_lo),
        "phase0": phase0_word(phase0),
        "fs": fs,
        "f_lo": f_lo,
        "phase0_rad": phase0,
        "source_npz": None,
    }


def write_params_svh(cases: list[dict]) -> None:
    """SystemVerilog header consumed by ``tb_ddc.sv``."""
    assert cases, "no cases"
    n = cases[0]["n_samples"]
    phase_inc = cases[0]["phase_inc"]
    phase0 = cases[0]["phase0"]
    for c in cases:
        assert c["n_samples"] == n
        assert c["phase_inc"] == phase_inc
        assert c["phase0"] == phase0

    names = ", ".join(f'"{c["name"]}"' for c in cases)
    lines = [
        "// Auto-generated by export_fixtures.py -- do not edit by hand.",
        "// Source: python/cryocontrol/dsp_ref/fixtures/{noiseless,noisy}.npz",
        f"localparam int DDC_N_SAMPLES = {n};",
        f"localparam int DDC_N_CASES   = {len(cases)};",
        f"localparam int DDC_TOL_LSB   = {TOL_LSB};",
        f"localparam logic [31:0] DDC_PHASE_INC = 32'h{phase_inc:08x};",
        f"localparam logic [31:0] DDC_PHASE0    = 32'h{phase0:08x};",
        f"localparam string DDC_CASE_NAMES [0:DDC_N_CASES-1] = '{{{names}}};",
        "",
    ]
    (VEC_DIR / "ddc_params.svh").write_text("\n".join(lines), encoding="utf-8")


def write_manifest(cases: list[dict]) -> None:
    rows = [
        "# DDC TB vectors -- regenerated from Phase 2 NPZ via dsp_ref.ddc",
        f"# Q1.14 scale=2^{FRAC_BITS}, tol_lsb={TOL_LSB}",
        "# case n_samples phase_inc phase0 source",
    ]
    for c in cases:
        rows.append(
            f"{c['name']} {c['n_samples']} "
            f"0x{c['phase_inc']:08x} 0x{c['phase0']:08x} {c['source_npz']}"
        )
    (VEC_DIR / "MANIFEST.txt").write_text("\n".join(rows) + "\n", encoding="utf-8")


def _repo_rel(path: Path) -> str:
    """Path relative to repo root when possible (portable MANIFEST)."""
    repo = TB_DIR.parents[2]  # hdl/tb/ddc -> repo
    try:
        return path.resolve().relative_to(repo.resolve()).as_posix()
    except ValueError:
        return path.as_posix()


def main() -> None:
    VEC_DIR.mkdir(parents=True, exist_ok=True)

    nl = load_fixture(NOISELESS)
    ny = load_fixture(NOISY)

    fs = float(nl["fs"])
    f_lo = float(nl["f_lo"])
    phase0 = float(nl["phase0"])
    # Noisy fixture must share NCO params with noiseless (same pipeline).
    assert float(ny["fs"]) == fs and float(ny["f_lo"]) == f_lo
    assert float(ny["phase0"]) == phase0

    cases = [
        export_case(
            "noiseless_s0",
            np.asarray(nl["input_iq_s0"]),
            fs=fs,
            f_lo=f_lo,
            phase0=phase0,
        ),
        export_case(
            "noiseless_s1",
            np.asarray(nl["input_iq_s1"]),
            fs=fs,
            f_lo=f_lo,
            phase0=phase0,
        ),
        export_case(
            "noisy",
            np.asarray(ny["input_iq"]),
            fs=fs,
            f_lo=f_lo,
            phase0=phase0,
        ),
    ]
    cases[0]["source_npz"] = _repo_rel(NOISELESS)
    cases[1]["source_npz"] = _repo_rel(NOISELESS)
    cases[2]["source_npz"] = _repo_rel(NOISY)

    write_params_svh(cases)
    write_manifest(cases)
    print(f"Wrote {len(cases)} cases ({cases[0]['n_samples']} samples each) -> {VEC_DIR}")


if __name__ == "__main__":
    main()
