// Auto-generated by export_fixtures.py -- do not edit by hand.
// Source: python/cryocontrol/dsp_ref/fixtures/{noiseless,noisy}.npz
localparam int SD_N_CASES      = 3;
localparam int SD_N_IN         = 1;  // one integrated IQ sample per case
// Bit-exact: no LSB tolerance on the 1-bit decision.
localparam int SD_THRESHOLD_Q  = 9962831;  // Q12.14
localparam string SD_CASE_NAMES [0:SD_N_CASES-1] = '{"noiseless_s0", "noiseless_s1", "noisy"};
