"""Export Phase 2 NPZ fixtures to ``$readmemh`` vectors for ``tb_fir``.

FIR stimulus = quantized post-DDC baseband from checked-in IF streams
(``dsp_ref.ddc``). Expected = quantized ``apply_fir`` then ``decimate``
(M from fixture). Coefficients = quantized fixture ``fir_coeffs``.

Quantizes I/Q and coeffs to signed Q1.14 (round-to-nearest, saturate).

Run from repo root (package importable)::

    python hdl/tb/fir/export_fixtures.py

Writes under ``hdl/tb/fir/vectors/``.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np

from cryocontrol.dsp_ref.ddc import ddc
from cryocontrol.dsp_ref.decimate import decimate
from cryocontrol.dsp_ref.fir import apply_fir
from cryocontrol.dsp_ref.fixtures import FIXTURES_DIR, load_fixture

FRAC_BITS = 14
SCALE = 1 << FRAC_BITS
# Matches docs/fixed_point_notes.md (fir module-TB compare): "a few LSBs"
# with 63-tap Q1.14 MAC vs float reference.
TOL_LSB = 8

TB_DIR = Path(__file__).resolve().parent
VEC_DIR = TB_DIR / "vectors"
NOISELESS = FIXTURES_DIR / "noiseless.npz"
NOISY = FIXTURES_DIR / "noisy.npz"


def float_to_q114(x: np.ndarray) -> np.ndarray:
    """Round-nearest float → signed Q1.14 int16 codes."""
    v = np.rint(np.asarray(x, dtype=np.float64) * SCALE)
    return np.clip(v, -32768, 32767).astype(np.int16)


def q114_to_hex_lines(codes: np.ndarray) -> list[str]:
    """Two's-complement 16-bit hex, one sample per line (for ``$readmemh``)."""
    u = codes.astype(np.int16).view(np.uint16)
    return [f"{int(v):04x}" for v in u]


def write_mem(path: Path, codes: np.ndarray) -> None:
    path.write_text("\n".join(q114_to_hex_lines(codes)) + "\n", encoding="utf-8")


def export_case(
    name: str,
    input_iq: np.ndarray,
    fir_coeffs: np.ndarray,
    *,
    fs: float,
    f_lo: float,
    phase0: float,
    decim_factor: int,
) -> dict:
    """Write in/exp I/Q mem files; return metadata for params."""
    baseband = ddc(input_iq, fs=fs, f_lo=f_lo, phase0=phase0)
    filtered = apply_fir(baseband, fir_coeffs)
    decimated = decimate(filtered, decim_factor)

    in_i = float_to_q114(np.real(baseband))
    in_q = float_to_q114(np.imag(baseband))
    exp_i = float_to_q114(np.real(decimated))
    exp_q = float_to_q114(np.imag(decimated))

    write_mem(VEC_DIR / f"{name}_in_i.mem", in_i)
    write_mem(VEC_DIR / f"{name}_in_q.mem", in_q)
    write_mem(VEC_DIR / f"{name}_exp_i.mem", exp_i)
    write_mem(VEC_DIR / f"{name}_exp_q.mem", exp_q)

    return {
        "name": name,
        "n_in": int(baseband.size),
        "n_out": int(decimated.size),
        "decim_factor": int(decim_factor),
        "num_taps": int(np.asarray(fir_coeffs).size),
        "fs": fs,
        "source_npz": None,
    }


def write_coeffs_mem(fir_coeffs: np.ndarray) -> None:
    """Shared Q1.14 coefficient ROM for future DUT (and TB documentation)."""
    codes = float_to_q114(np.asarray(fir_coeffs, dtype=np.float64))
    write_mem(VEC_DIR / "fir_coeffs.mem", codes)


def write_params_svh(cases: list[dict], *, num_taps: int, decim: int) -> None:
    """SystemVerilog header consumed by ``tb_fir.sv``."""
    assert cases, "no cases"
    n_in = cases[0]["n_in"]
    n_out = cases[0]["n_out"]
    for c in cases:
        assert c["n_in"] == n_in
        assert c["n_out"] == n_out
        assert c["decim_factor"] == decim
        assert c["num_taps"] == num_taps
    assert n_out == n_in // decim

    names = ", ".join(f'"{c["name"]}"' for c in cases)
    lines = [
        "// Auto-generated by export_fixtures.py -- do not edit by hand.",
        "// Source: python/cryocontrol/dsp_ref/fixtures/{noiseless,noisy}.npz",
        f"localparam int FIR_N_IN       = {n_in};",
        f"localparam int FIR_N_OUT      = {n_out};",
        f"localparam int FIR_N_CASES    = {len(cases)};",
        f"localparam int FIR_NUM_TAPS   = {num_taps};",
        f"localparam int FIR_DECIM_M    = {decim};",
        f"localparam int FIR_TOL_LSB    = {TOL_LSB};",
        f"localparam string FIR_CASE_NAMES [0:FIR_N_CASES-1] = '{{{names}}};",
        "",
    ]
    (VEC_DIR / "fir_params.svh").write_text("\n".join(lines), encoding="utf-8")


def write_manifest(cases: list[dict], *, num_taps: int, decim: int) -> None:
    rows = [
        "# FIR TB vectors -- regenerated from Phase 2 NPZ via dsp_ref.ddc/fir/decimate",
        f"# Q1.14 scale=2^{FRAC_BITS}, tol_lsb={TOL_LSB}, taps={num_taps}, M={decim}",
        "# case n_in n_out source",
    ]
    for c in cases:
        rows.append(
            f"{c['name']} {c['n_in']} {c['n_out']} {c['source_npz']}"
        )
    (VEC_DIR / "MANIFEST.txt").write_text("\n".join(rows) + "\n", encoding="utf-8")


def _repo_rel(path: Path) -> str:
    """Path relative to repo root when possible (portable MANIFEST)."""
    repo = TB_DIR.parents[2]  # hdl/tb/fir -> repo
    try:
        return path.resolve().relative_to(repo.resolve()).as_posix()
    except ValueError:
        return path.as_posix()


def main() -> None:
    VEC_DIR.mkdir(parents=True, exist_ok=True)

    nl = load_fixture(NOISELESS)
    ny = load_fixture(NOISY)

    fs = float(nl["fs"])
    f_lo = float(nl["f_lo"])
    phase0 = float(nl["phase0"])
    fir_coeffs = np.asarray(nl["fir_coeffs"], dtype=np.float64)
    decim = int(nl["decim_factor"])
    num_taps = int(nl["fir_num_taps"])

    assert float(ny["fs"]) == fs and float(ny["f_lo"]) == f_lo
    assert float(ny["phase0"]) == phase0
    assert int(ny["decim_factor"]) == decim
    assert int(ny["fir_num_taps"]) == num_taps
    assert np.allclose(np.asarray(ny["fir_coeffs"]), fir_coeffs)
    assert fir_coeffs.size == num_taps

    write_coeffs_mem(fir_coeffs)

    cases = [
        export_case(
            "noiseless_s0",
            np.asarray(nl["input_iq_s0"]),
            fir_coeffs,
            fs=fs,
            f_lo=f_lo,
            phase0=phase0,
            decim_factor=decim,
        ),
        export_case(
            "noiseless_s1",
            np.asarray(nl["input_iq_s1"]),
            fir_coeffs,
            fs=fs,
            f_lo=f_lo,
            phase0=phase0,
            decim_factor=decim,
        ),
        export_case(
            "noisy",
            np.asarray(ny["input_iq"]),
            fir_coeffs,
            fs=fs,
            f_lo=f_lo,
            phase0=phase0,
            decim_factor=decim,
        ),
    ]
    cases[0]["source_npz"] = _repo_rel(NOISELESS)
    cases[1]["source_npz"] = _repo_rel(NOISELESS)
    cases[2]["source_npz"] = _repo_rel(NOISY)

    write_params_svh(cases, num_taps=num_taps, decim=decim)
    write_manifest(cases, num_taps=num_taps, decim=decim)
    print(
        f"Wrote {len(cases)} cases "
        f"(n_in={cases[0]['n_in']}, n_out={cases[0]['n_out']}, "
        f"taps={num_taps}, M={decim}) -> {VEC_DIR}"
    )


if __name__ == "__main__":
    main()
