// Auto-generated by export_fixtures.py -- do not edit by hand.
// Source: python/cryocontrol/dsp_ref/fixtures/{noiseless,noisy}.npz
localparam int RC_N_SAMPLES         = 4096;
localparam int RC_N_CASES           = 3;
localparam int RC_TOL_LSB           = 16384;  // abs err <= 1.0 in Q12.14
localparam int RC_NUM_TAPS          = 63;
localparam int RC_DECIM_M           = 4;
localparam int RC_INTEGRATE_START   = 8;
localparam int RC_INTEGRATE_LENGTH  = 1016;
localparam int RC_THRESHOLD_Q       = 9962831;  // Q12.14
localparam logic [31:0] RC_PHASE_INC = 32'h1999999a;
localparam logic [31:0] RC_PHASE0    = 32'h00000000;
localparam string RC_CASE_NAMES [0:RC_N_CASES-1] = '{"noiseless_s0", "noiseless_s1", "noisy"};
