"""Export Phase 2 NPZ fixtures to ``$readmemh`` vectors for ``tb_integration``.

Stimulus = quantized post-FIR/decim IQ from the dsp_ref chain
(``ddc → apply_fir → decimate``). Expected = quantized ``integrate`` of that
stream (window from fixture ``integrate_start`` / through end).

Input quantized to signed Q1.14; expected integrated I/Q to signed Q12.14
(26-bit value in a 32-bit hex word), matching ``docs/fixed_point_notes.md``.

Run from repo root (package importable)::

    python hdl/tb/integration/export_fixtures.py

Writes under ``hdl/tb/integration/vectors/``.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np

from cryocontrol.dsp_ref.ddc import ddc
from cryocontrol.dsp_ref.decimate import decimate
from cryocontrol.dsp_ref.fir import apply_fir
from cryocontrol.dsp_ref.fixtures import FIXTURES_DIR, load_fixture
from cryocontrol.dsp_ref.integrate import integrate

FRAC_BITS = 14
SCALE = 1 << FRAC_BITS
# Q12.14 abs error ≤ 1.0 → 1.0 * 2^14 LSBs (docs/fixed_point_notes.md).
TOL_LSB = SCALE
# Signed Q12.14 lives in 26 bits; clip to that range before packing into 32-bit.
Q1214_MAX = (1 << 25) - 1
Q1214_MIN = -(1 << 25)

TB_DIR = Path(__file__).resolve().parent
VEC_DIR = TB_DIR / "vectors"
NOISELESS = FIXTURES_DIR / "noiseless.npz"
NOISY = FIXTURES_DIR / "noisy.npz"


def float_to_q114(x: np.ndarray) -> np.ndarray:
    """Round-nearest float → signed Q1.14 int16 codes."""
    v = np.rint(np.asarray(x, dtype=np.float64) * SCALE)
    return np.clip(v, -32768, 32767).astype(np.int16)


def float_to_q1214_scalar(x: float) -> int:
    """Round-nearest float → signed Q12.14 code (26-bit range)."""
    v = int(np.rint(float(x) * SCALE))
    return int(np.clip(v, Q1214_MIN, Q1214_MAX))


def q114_to_hex_lines(codes: np.ndarray) -> list[str]:
    """Two's-complement 16-bit hex, one sample per line (for ``$readmemh``)."""
    u = codes.astype(np.int16).view(np.uint16)
    return [f"{int(v):04x}" for v in u]


def q1214_to_hex_line(code: int) -> str:
    """Two's-complement 32-bit hex (sign-extended Q12.14) for ``$readmemh``."""
    return f"{code & 0xFFFFFFFF:08x}"


def write_mem16(path: Path, codes: np.ndarray) -> None:
    path.write_text("\n".join(q114_to_hex_lines(codes)) + "\n", encoding="utf-8")


def write_mem32_scalar(path: Path, code: int) -> None:
    path.write_text(q1214_to_hex_line(code) + "\n", encoding="utf-8")


def resolve_integrate_length(n_in: int, start: int, length_raw: int) -> int:
    """Fixture ``integrate_length`` of −1 means through end of the stream."""
    if length_raw < 0:
        return n_in - start
    return int(length_raw)


def export_case(
    name: str,
    input_iq: np.ndarray,
    fir_coeffs: np.ndarray,
    *,
    fs: float,
    f_lo: float,
    phase0: float,
    decim_factor: int,
    integrate_start: int,
    integrate_length_raw: int,
    fixture_output_iq: complex,
) -> dict:
    """Write in/exp I/Q mem files; return metadata for params."""
    baseband = ddc(input_iq, fs=fs, f_lo=f_lo, phase0=phase0)
    filtered = apply_fir(baseband, fir_coeffs)
    decimated = decimate(filtered, decim_factor)
    n_in = int(decimated.size)
    integ_len = resolve_integrate_length(n_in, integrate_start, integrate_length_raw)
    iq = integrate(decimated, start=integrate_start, length=integ_len)

    # Sanity: chain integrate must match checked-in fixture output_iq_*.
    if abs(iq - complex(fixture_output_iq)) > 1e-6:
        raise AssertionError(
            f"{name}: integrate()={iq!r} != fixture output_iq={fixture_output_iq!r}"
        )

    in_i = float_to_q114(np.real(decimated))
    in_q = float_to_q114(np.imag(decimated))
    exp_i = float_to_q1214_scalar(float(np.real(iq)))
    exp_q = float_to_q1214_scalar(float(np.imag(iq)))

    write_mem16(VEC_DIR / f"{name}_in_i.mem", in_i)
    write_mem16(VEC_DIR / f"{name}_in_q.mem", in_q)
    write_mem32_scalar(VEC_DIR / f"{name}_exp_i.mem", exp_i)
    write_mem32_scalar(VEC_DIR / f"{name}_exp_q.mem", exp_q)

    return {
        "name": name,
        "n_in": n_in,
        "integrate_start": int(integrate_start),
        "integrate_length": int(integ_len),
        "exp_i": exp_i,
        "exp_q": exp_q,
        "source_npz": None,
    }


def write_params_svh(cases: list[dict]) -> None:
    """SystemVerilog header consumed by ``tb_integration.sv``."""
    assert cases, "no cases"
    n_in = cases[0]["n_in"]
    start = cases[0]["integrate_start"]
    length = cases[0]["integrate_length"]
    for c in cases:
        assert c["n_in"] == n_in
        assert c["integrate_start"] == start
        assert c["integrate_length"] == length
    assert length == n_in - start

    names = ", ".join(f'"{c["name"]}"' for c in cases)
    lines = [
        "// Auto-generated by export_fixtures.py -- do not edit by hand.",
        "// Source: python/cryocontrol/dsp_ref/fixtures/{noiseless,noisy}.npz",
        f"localparam int INT_N_IN              = {n_in};",
        f"localparam int INT_N_CASES           = {len(cases)};",
        f"localparam int INT_INTEGRATE_START   = {start};",
        f"localparam int INT_INTEGRATE_LENGTH  = {length};",
        f"localparam int INT_TOL_LSB           = {TOL_LSB};",
        f"localparam string INT_CASE_NAMES [0:INT_N_CASES-1] = '{{{names}}};",
        "",
    ]
    (VEC_DIR / "integration_params.svh").write_text("\n".join(lines), encoding="utf-8")


def write_manifest(cases: list[dict]) -> None:
    rows = [
        "# Integration TB vectors -- regenerated from Phase 2 NPZ via",
        "# dsp_ref.ddc -> fir -> decimate -> integrate",
        f"# in=Q1.14 out=Q12.14 scale=2^{FRAC_BITS} tol_lsb={TOL_LSB}",
        f"# window start={cases[0]['integrate_start']} length={cases[0]['integrate_length']}",
        "# case n_in start length exp_i exp_q source",
    ]
    for c in cases:
        rows.append(
            f"{c['name']} {c['n_in']} {c['integrate_start']} {c['integrate_length']} "
            f"{c['exp_i']} {c['exp_q']} {c['source_npz']}"
        )
    (VEC_DIR / "MANIFEST.txt").write_text("\n".join(rows) + "\n", encoding="utf-8")


def _repo_rel(path: Path) -> str:
    """Path relative to repo root when possible (portable MANIFEST)."""
    repo = TB_DIR.parents[2]  # hdl/tb/integration -> repo
    try:
        return path.resolve().relative_to(repo.resolve()).as_posix()
    except ValueError:
        return path.as_posix()


def main() -> None:
    VEC_DIR.mkdir(parents=True, exist_ok=True)

    nl = load_fixture(NOISELESS)
    ny = load_fixture(NOISY)

    fs = float(nl["fs"])
    f_lo = float(nl["f_lo"])
    phase0 = float(nl["phase0"])
    fir_coeffs = np.asarray(nl["fir_coeffs"], dtype=np.float64)
    decim = int(nl["decim_factor"])
    integ_start = int(nl["integrate_start"])
    integ_len_raw = int(nl["integrate_length"])

    assert float(ny["fs"]) == fs and float(ny["f_lo"]) == f_lo
    assert float(ny["phase0"]) == phase0
    assert int(ny["decim_factor"]) == decim
    assert int(ny["integrate_start"]) == integ_start
    assert int(ny["integrate_length"]) == integ_len_raw
    assert np.allclose(np.asarray(ny["fir_coeffs"]), fir_coeffs)

    cases = [
        export_case(
            "noiseless_s0",
            np.asarray(nl["input_iq_s0"]),
            fir_coeffs,
            fs=fs,
            f_lo=f_lo,
            phase0=phase0,
            decim_factor=decim,
            integrate_start=integ_start,
            integrate_length_raw=integ_len_raw,
            fixture_output_iq=complex(nl["output_iq_s0"]),
        ),
        export_case(
            "noiseless_s1",
            np.asarray(nl["input_iq_s1"]),
            fir_coeffs,
            fs=fs,
            f_lo=f_lo,
            phase0=phase0,
            decim_factor=decim,
            integrate_start=integ_start,
            integrate_length_raw=integ_len_raw,
            fixture_output_iq=complex(nl["output_iq_s1"]),
        ),
        export_case(
            "noisy",
            np.asarray(ny["input_iq"]),
            fir_coeffs,
            fs=fs,
            f_lo=f_lo,
            phase0=phase0,
            decim_factor=decim,
            integrate_start=integ_start,
            integrate_length_raw=integ_len_raw,
            fixture_output_iq=complex(ny["output_iq"]),
        ),
    ]
    cases[0]["source_npz"] = _repo_rel(NOISELESS)
    cases[1]["source_npz"] = _repo_rel(NOISELESS)
    cases[2]["source_npz"] = _repo_rel(NOISY)

    write_params_svh(cases)
    write_manifest(cases)
    print(
        f"Wrote {len(cases)} cases "
        f"(n_in={cases[0]['n_in']}, start={cases[0]['integrate_start']}, "
        f"length={cases[0]['integrate_length']}) -> {VEC_DIR}"
    )


if __name__ == "__main__":
    main()
