// Auto-generated by export_fixtures.py -- do not edit by hand.
// Source: python/cryocontrol/dsp_ref/fixtures/{noiseless,noisy}.npz
localparam int FIR_N_IN       = 4096;
localparam int FIR_N_OUT      = 1024;
localparam int FIR_N_CASES    = 3;
localparam int FIR_NUM_TAPS   = 63;
localparam int FIR_DECIM_M    = 4;
localparam int FIR_TOL_LSB    = 8;
localparam string FIR_CASE_NAMES [0:FIR_N_CASES-1] = '{"noiseless_s0", "noiseless_s1", "noisy"};
