"""Export Phase 2 NPZ fixtures to ``$readmemh`` vectors for ``tb_state_discrim``.

Stimulus = quantized integrated IQ from fixture ``output_iq_*`` (Q12.14).
Expected = fixture ``decision_*`` (1-bit), cross-checked against
``dsp_ref.threshold.discriminate`` and a Q12.14 integer compare
(``Re(iq_q) >= threshold_q``) so HDL bit-exact matches stay aligned with
``docs/fixed_point_notes.md`` § state_discrim.

Run from repo root (package importable)::

    python hdl/tb/state_discrim/export_fixtures.py

Writes under ``hdl/tb/state_discrim/vectors/``.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np

from cryocontrol.dsp_ref.fixtures import FIXTURES_DIR, load_fixture
from cryocontrol.dsp_ref.threshold import discriminate

FRAC_BITS = 14
SCALE = 1 << FRAC_BITS
# Signed Q12.14 lives in 26 bits; clip to that range before packing into 32-bit.
Q1214_MAX = (1 << 25) - 1
Q1214_MIN = -(1 << 25)

TB_DIR = Path(__file__).resolve().parent
VEC_DIR = TB_DIR / "vectors"
NOISELESS = FIXTURES_DIR / "noiseless.npz"
NOISY = FIXTURES_DIR / "noisy.npz"


def float_to_q1214_scalar(x: float) -> int:
    """Round-nearest float → signed Q12.14 code (26-bit range)."""
    v = int(np.rint(float(x) * SCALE))
    return int(np.clip(v, Q1214_MIN, Q1214_MAX))


def q1214_to_hex_line(code: int) -> str:
    """Two's-complement 32-bit hex (sign-extended Q12.14) for ``$readmemh``."""
    return f"{code & 0xFFFFFFFF:08x}"


def write_mem32_scalar(path: Path, code: int) -> None:
    path.write_text(q1214_to_hex_line(code) + "\n", encoding="utf-8")


def write_mem1_scalar(path: Path, bit: int) -> None:
    """Single 1-bit expected decision as one hex digit for ``$readmemh``."""
    if bit not in (0, 1):
        raise ValueError(f"decision must be 0 or 1, got {bit}")
    path.write_text(f"{bit:01x}\n", encoding="utf-8")


def export_case(
    name: str,
    output_iq: complex,
    fixture_decision: int,
    threshold: float,
    threshold_q: int,
) -> dict:
    """Write in I/Q + expected decision mem files; return metadata."""
    dec_float = discriminate(output_iq, threshold=threshold)
    assert isinstance(dec_float, int)
    if dec_float != int(fixture_decision):
        raise AssertionError(
            f"{name}: discriminate({output_iq!r}, {threshold})={dec_float} "
            f"!= fixture decision={fixture_decision}"
        )

    in_i = float_to_q1214_scalar(float(np.real(output_iq)))
    in_q = float_to_q1214_scalar(float(np.imag(output_iq)))
    dec_q = 1 if in_i >= threshold_q else 0
    if dec_q != int(fixture_decision):
        raise AssertionError(
            f"{name}: Q12.14 compare (i={in_i} >= thr={threshold_q}) → {dec_q} "
            f"!= fixture decision={fixture_decision}"
        )

    write_mem32_scalar(VEC_DIR / f"{name}_in_i.mem", in_i)
    write_mem32_scalar(VEC_DIR / f"{name}_in_q.mem", in_q)
    write_mem1_scalar(VEC_DIR / f"{name}_exp_decision.mem", int(fixture_decision))

    return {
        "name": name,
        "in_i": in_i,
        "in_q": in_q,
        "exp_decision": int(fixture_decision),
        "source_npz": None,
    }


def write_params_svh(cases: list[dict], threshold_q: int) -> None:
    """SystemVerilog header consumed by ``tb_state_discrim.sv``."""
    assert cases, "no cases"
    names = ", ".join(f'"{c["name"]}"' for c in cases)
    lines = [
        "// Auto-generated by export_fixtures.py -- do not edit by hand.",
        "// Source: python/cryocontrol/dsp_ref/fixtures/{noiseless,noisy}.npz",
        f"localparam int SD_N_CASES      = {len(cases)};",
        "localparam int SD_N_IN         = 1;  // one integrated IQ sample per case",
        "// Bit-exact: no LSB tolerance on the 1-bit decision.",
        f"localparam int SD_THRESHOLD_Q  = {threshold_q};  // Q12.14",
        f"localparam string SD_CASE_NAMES [0:SD_N_CASES-1] = '{{{names}}};",
        "",
    ]
    (VEC_DIR / "state_discrim_params.svh").write_text(
        "\n".join(lines), encoding="utf-8"
    )


def write_manifest(cases: list[dict], threshold: float, threshold_q: int) -> None:
    rows = [
        "# State-discrim TB vectors -- regenerated from Phase 2 NPZ",
        "# stimulus = quantize_Q12.14(fixture output_iq_*)",
        "# expected = fixture decision_* (bit-exact vs Re(iq_q) >= threshold_q)",
        f"# threshold_float={threshold} threshold_q1214={threshold_q}",
        "# case in_i in_q exp_decision source",
    ]
    for c in cases:
        rows.append(
            f"{c['name']} {c['in_i']} {c['in_q']} {c['exp_decision']} "
            f"{c['source_npz']}"
        )
    (VEC_DIR / "MANIFEST.txt").write_text("\n".join(rows) + "\n", encoding="utf-8")


def _repo_rel(path: Path) -> str:
    """Path relative to repo root when possible (portable MANIFEST)."""
    repo = TB_DIR.parents[2]  # hdl/tb/state_discrim -> repo
    try:
        return path.resolve().relative_to(repo.resolve()).as_posix()
    except ValueError:
        return path.as_posix()


def main() -> None:
    VEC_DIR.mkdir(parents=True, exist_ok=True)

    nl = load_fixture(NOISELESS)
    ny = load_fixture(NOISY)

    threshold = float(nl["threshold"])
    assert float(ny["threshold"]) == threshold
    threshold_q = float_to_q1214_scalar(threshold)

    cases = [
        export_case(
            "noiseless_s0",
            complex(nl["output_iq_s0"]),
            int(nl["decision_s0"]),
            threshold,
            threshold_q,
        ),
        export_case(
            "noiseless_s1",
            complex(nl["output_iq_s1"]),
            int(nl["decision_s1"]),
            threshold,
            threshold_q,
        ),
        export_case(
            "noisy",
            complex(ny["output_iq"]),
            int(ny["decision"]),
            threshold,
            threshold_q,
        ),
    ]
    cases[0]["source_npz"] = _repo_rel(NOISELESS)
    cases[1]["source_npz"] = _repo_rel(NOISELESS)
    cases[2]["source_npz"] = _repo_rel(NOISY)

    write_params_svh(cases, threshold_q)
    write_manifest(cases, threshold, threshold_q)
    print(
        f"Wrote {len(cases)} cases "
        f"(threshold_q={threshold_q}) -> {VEC_DIR}"
    )


if __name__ == "__main__":
    main()
