// Auto-generated by export_fixtures.py -- do not edit by hand.
// Source: python/cryocontrol/dsp_ref/fixtures/{noiseless,noisy}.npz
localparam int DDC_N_SAMPLES = 4096;
localparam int DDC_N_CASES   = 3;
localparam int DDC_TOL_LSB   = 4;
localparam logic [31:0] DDC_PHASE_INC = 32'h1999999a;
localparam logic [31:0] DDC_PHASE0    = 32'h00000000;
localparam string DDC_CASE_NAMES [0:DDC_N_CASES-1] = '{"noiseless_s0", "noiseless_s1", "noisy"};
