// Auto-generated by export_fixtures.py -- do not edit by hand.
// Source: python/cryocontrol/dsp_ref/fixtures/{noiseless,noisy}.npz
localparam int INT_N_IN              = 1024;
localparam int INT_N_CASES           = 3;
localparam int INT_INTEGRATE_START   = 8;
localparam int INT_INTEGRATE_LENGTH  = 1016;
localparam int INT_TOL_LSB           = 16384;
localparam string INT_CASE_NAMES [0:INT_N_CASES-1] = '{"noiseless_s0", "noiseless_s1", "noisy"};
